### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by bpvarsity** [akai-katto/dandere2x#154]
After 20 seconds of running I get a broken pipe error. Any ideas what I did wrong? 

Waifu2x-Vulkan
Denoise Level 4
Scale 2x 
Image Q 95
Block size 20

2020-10-30 10:00:32,050 INFO     context.py log_all_variables: rotate : 0
2020-10-30 10:00:32,051 INFO     context.py log_all_variables: frame_rate : 30.0
2020-10-30 10:00:32,051 INFO     context.py log_all_variables: frame_count : 275
2020-10-30 10:00:32,052 INFO     context.py log_all_variables: resume_session : False
2020-10-30 10:00:32,052 INFO     context.py log_all_variables: last_saved_frame : 1
2020-10-30 10:00:32,056 INFO     context.py log_all_variables: incomplete_video : none
2020-10-30 10:00:33,015 INFO     dandere2x.py __upscale_first_frame: Time to upscale a single frame: 0.74
2020-10-30 10:00:33,018 INFO     dandere2x_cpp.py run     : ['C:\\Users\\Alex\\Desktop\\2.1.3\\externals\\dandere2x_cpp.exe', 'C:\\Users\\Alex\\Desktop\\2.1.3\\workspace\\default_workspace\\', '275', '20', '8', 'r', '1', '.jpg']
2020-10-30 10:00:33,018 INFO     merge.py run     : Started
2020-10-30 10:00:33,018 INFO     residual.py run     : Run called.
2020-10-30 10:00:33,019 INFO     abstract_upscaler.py run     : Run called.
2020-10-30 10:00:33,019 INFO     status.py run     : Run called.
2020-10-30 10:00:33,020 INFO     pipe_thread.py run     : Run Called
Exception in thread Pipe Thread:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "wrappers\ffmpeg\pipe_thread.py", line 49, in run
  File "PIL\Image.py", line 2158, in save
  File "PIL\JpegImagePlugin.py", line 765, in _save
  File "PIL\ImageFile.py", line 538, in _save
BrokenPipeError: [Errno 32] Broken pipe

**Comment by aka-katto** [comment]
https://github.com/aka-katto/dandere2x/releases/tag/2.1.5

does this release fix it? It's a patch

**Comment by akai-katto** [comment]
Fixed this with a numpy work-around

**Comment by DemersM** [comment]
I had the same problem and found out the the libx264 encoder was not enabled in my ffmpeg build
