### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by lovesegfault** [akai-katto/dandere2x#159]
It'd be nice if the project had a Dockerfile or published Docker images to make it easier to play with in on a Linux box.

**Comment by aka-katto** [comment]
Definitely. 

I'll try wrapping up my current branch and start implementing a docker image

**Comment by lovesegfault** [comment]
Thank you! Much appreciated :)

**Comment by akai-katto** [comment]
Leaving this here for others to help me:

https://github.com/akai-katto/dandere2x/discussions/165

I'm having issues getting the docker image to work with vulkan and seeking support from others.

**Comment by akai-katto** [comment]
https://www.reddit.com/r/Dandere2x/comments/kmvxkt/dandere2x_docker_image_ready_for_testing/? 

:]

**Comment by lovesegfault** [comment]
@akai-katto Just tested, seems to be missing ffmpeg?

```
❯ docker run \
    --rm \
    -it \
    --gpus all \
    --mount "type=tmpfs,destination=/tmp" \
    -v /dev/dri:/dev/dri \
    -v $PWD:/host \
    akaikatto/dandere2x \
    -p singleprocess \
    -ws ./workspace \
    -i ~/tmp/sample_original.mp4 \
    -o ./sample_output.mp4
workspace : /dandere2x/dandere2x/src/workspace
scale_factor : 2
quality_minimum : 85
denoise_level : 3
block_size : 30
output_file : /dandere2x/dandere2x/src/sample_output.mp4
input_file : /home/bemeurer/tmp/sample_original.mp4
output_options : {'realsr_ncnn_vulkan': {'output_options': {'-g': None, '-load-proc-save_threads': None, '-model-path': None, '-tile-size': 200, '-verbose': None}}, 'ffmpeg': {'-hwaccel': True, 'pre_process_video': {'output_options': {'-pix_fmt': None, '-vsync': 'cfr', '-crf': 17, '-vf': ['noise=c1s=8:c0f=u']}}, 'convert_video_to_gif': {'output_options': {'-pix_fmt': 'yuv420p', '-r': 15}}, 'pipe_video': {'output_options': {'-loglevel': 'panic', '-y': '-f', 'image2pipe': True, '-i': '-', '-vcodec': 'libx264', '-preset': 'medium', '-qscale': 5, '-crf': 17, '-vf': [' deband=range=8:blur=false, pp7=qp=2:mode=medium']}}}, 'waifu2x_ncnn_vulkan': {'output_options': {'-g': None, '-load-proc-save_threads': None, '-tile-size': 200, '-verbose': None}}, 'waifu2x_converter': {'output_options': {'--block-size': None, '--disable-gpu': None, '--force-OpenCL': True, '--image-quality': None, '--jobs': None, '--mode': None, '--model-dir': None, '--output-format': None, '--png-compression': None, '--processor': None, '--silent': True}}, 'waifu2x_caffe': {'output_options': {'-batch_size': None, '-crop_size': None, '-gpu': None, '-model_dir': None, '-output_depth': None, '-output_quality': None, '-process': 'cudnn', '-tta': None}}}
name : Master Service Request
processing_type : ProcessingType.SINGLE_PROCESS
upscale_engine : UpscalingEngineType.VULKAN
attempting to make or clear /dandere2x/dandere2x/src/workspace
Traceback (most recent call last):
  File "/dandere2x/dandere2x/src/main.py", line 44, in <module>
    main()
  File "/dandere2x/dandere2x/src/main.py", line 39, in main
    cli_start()
  File "/dandere2x/dandere2x/src/main.py", line 14, in cli_start
    dandere2x_session = Dandere2x(service_request=root_service_request)
  File "/dandere2x/dandere2x/src/dandere2x/__init__.py", line 25, in __init__
    self._root_service_thread = anonymous_dandere2x_service(service_request=self._service_request)
  File "/dandere2x/dandere2x/src/dandere2x/dandere2x_service/service_types/singleprocess_service.py", line 23, in __init__
    input_video=self._service_request.input_file),\
  File "/dandere2x/dandere2x/src/dandere2x/dandere2xlib/wrappers/ffmpeg/ffmpeg.py", line 99, in is_file_video
    return_bytes = subprocess.run(execute, check=True, stdout=subprocess.PIPE).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffprobe', '-i', '/home/bemeurer/tmp/sample_original.mp4', '-v', 'quiet']' returned non-zero exit status 1.
Press key to exit.ls
```

**Comment by akai-katto** [comment]
I saw you commented (email notif)  + but I can't find the comment here, hopefully you got it resolved

**Comment by lovesegfault** [comment]
> I saw you commented (email notif) + but I can't find the comment here, hopefully you got it resolved

Yeah, I deleted it because it was just me being silly. I forgot to replace `./foo.mp4` with `/host/foo.mp4` :P 

I'm testing it right now and it seems to be working!
