### ISSUE TITLE
ZeroDivisionError: Fraction(0, 0)

### ISSUE THREAD

**Issue by TheProgramableTurtle** [akai-katto/dandere2x#171]
Using Vulkan, all default settings on singleprocess and multiprocess, I get this output.
```
config file: multiprocess
attempting to make or clear D:\Programs\dandere2x\3.0\3.0\workspace\gui
setting json {'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10', 'profile': 'High', 'codec_type': 'video', 'codec_time_base': '1/2000', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1920, 'height': 1080, 'coded_width': 1920, 'coded_height': 1088, 'has_b_frames': 2, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '16:9', 'pix_fmt': 'yuv420p', 'level': 42, 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'true', 'nal_length_size': '4', 'r_frame_rate': '60/1', 'avg_frame_rate': '1000/1', 'time_base': '1/1000', 'start_pts': 0, 'start_time': '0.000000', 'bits_per_raw_sample': '8', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'DURATION': '00:00:34.473000000'}}, {'index': 1, 'codec_name': 'aac', 'codec_long_name': 'AAC (Advanced Audio Coding)', 'profile': 'LC', 'codec_type': 'audio', 'codec_time_base': '1/44100', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'sample_fmt': 'fltp', 'sample_rate': '44100', 'channels': 2, 'channel_layout': 'stereo', 'bits_per_sample': 0, 'r_frame_rate': '0/0', 'avg_frame_rate': '0/0', 'time_base': '1/1000', 'start_pts': 0, 'start_time': '0.000000', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'DURATION': '00:00:34.481000000'}}], 'format': {'filename': 'D:\\Programs\\melonDS_0.9.1_win64\\Cutscene Upscale Indy\\out3.mkv', 'nb_streams': 2, 'nb_programs': 0, 'format_name': 'matroska,webm', 'format_long_name': 'Matroska / WebM', 'start_time': '0.000000', 'duration': '34.481000', 'size': '6435292', 'bit_rate': '1493063', 'probe_score': 100, 'tags': {'ENCODER': 'Lavf58.12.100'}}}
setting json {'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10', 'profile': 'High', 'codec_type': 'video', 'codec_time_base': '1/2000', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1920, 'height': 1080, 'coded_width': 1920, 'coded_height': 1088, 'has_b_frames': 2, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '16:9', 'pix_fmt': 'yuv420p', 'level': 42, 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'true', 'nal_length_size': '4', 'r_frame_rate': '60/1', 'avg_frame_rate': '1000/1', 'time_base': '1/1000', 'start_pts': 0, 'start_time': '0.000000', 'bits_per_raw_sample': '8', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'DURATION': '00:00:34.473000000'}}, {'index': 1, 'codec_name': 'aac', 'codec_long_name': 'AAC (Advanced Audio Coding)', 'profile': 'LC', 'codec_type': 'audio', 'codec_time_base': '1/44100', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'sample_fmt': 'fltp', 'sample_rate': '44100', 'channels': 2, 'channel_layout': 'stereo', 'bits_per_sample': 0, 'r_frame_rate': '0/0', 'avg_frame_rate': '0/0', 'time_base': '1/1000', 'start_pts': 0, 'start_time': '0.000000', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'DURATION': '00:00:34.481000000'}}], 'format': {'filename': 'D:\\Programs\\melonDS_0.9.1_win64\\Cutscene Upscale Indy\\out3.mkv', 'nb_streams': 2, 'nb_programs': 0, 'format_name': 'matroska,webm', 'format_long_name': 'Matroska / WebM', 'start_time': '0.000000', 'duration': '34.481000', 'size': '6435292', 'bit_rate': '1493063', 'probe_score': 100, 'tags': {'ENCODER': 'Lavf58.12.100'}}}
ffmpeg version N-93471-gf8fa8bbf22 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.105 / 58. 47.105
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, matroska,webm, from 'D:\Programs\melonDS_0.9.1_win64\Cutscene Upscale Indy\out3.mkv':
  Metadata:
    ENCODER         : Lavf58.12.100
  Duration: 00:00:34.48, start: 0.000000, bitrate: 1493 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 1k fps, 60 tbr, 1k tbn, 120 tbc (default)
    Metadata:
      DURATION        : 00:00:34.473000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:00:34.481000000
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
[libx264 @ 000002911df99380] using SAR=1/1
[libx264 @ 000002911df99380] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000002911df99380] profile Progressive High, level 6.1, 4:2:0, 8-bit
[libx264 @ 000002911df99380] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=17.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[segment @ 000002911d561cc0] Opening 'D:\Programs\dandere2x\3.0\3.0\workspace\gui\split_video0.mkv' for writing
Output #0, segment, to 'D:\Programs\dandere2x\3.0\3.0\workspace\gui\split_video%d.mkv':
  Metadata:
    encoder         : Lavf58.26.101
    Stream #0:0: Video: h264 (libx264), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 1k fps, 1k tbn, 1k tbc (default)
    Metadata:
      DURATION        : 00:00:34.473000000
      encoder         : Lavc58.47.105 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: vorbis (libvorbis), 44100 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:00:34.481000000
      encoder         : Lavc58.47.105 libvorbis
More than 1000 frames duplicatedN/A time=00:00:01.21 bitrate=N/A dup=916 drop=0 speed=0.23x
More than 10000 frames duplicated/A time=00:00:10.76 bitrate=N/A dup=9956 drop=0 speed=0.171x
[segment @ 000002911d561cc0] Opening 'D:\Programs\dandere2x\3.0\3.0\workspace\gui\split_video1.mkv' for writing
[segment @ 000002911d561cc0] Opening 'D:\Programs\dandere2x\3.0\3.0\workspace\gui\split_video2.mkv' for writing
[matroska,webm @ 000002911d559ac0] Invalid length 0x164 > 0x62306c in parentrop=0 speed=0.173x
frame=34489 fps=171 q=-1.0 Lsize=N/A time=00:00:34.48 bitrate=N/A dup=32436 drop=0 speed=0.171x
video:129428kB audio:349kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: unknown
[libx264 @ 000002911df99380] frame I:156   Avg QP:13.31  size:374497
[libx264 @ 000002911df99380] frame P:8688  Avg QP:16.30  size:  8031
[libx264 @ 000002911df99380] frame B:25645 Avg QP:29.10  size:   169
[libx264 @ 000002911df99380] consecutive B-frames:  0.8%  0.1%  0.1% 99.0%
[libx264 @ 000002911df99380] mb I  I16..4:  8.1% 70.1% 21.8%
[libx264 @ 000002911df99380] mb P  I16..4:  0.1%  0.9%  0.2%  P16..4:  4.2%  0.9%  0.7%  0.0%  0.0%    skip:92.9%
[libx264 @ 000002911df99380] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  1.9%  0.0%  0.0%  direct: 0.0%  skip:98.1%  L0:38.4% L1:61.4% BI: 0.2%
[libx264 @ 000002911df99380] 8x8 transform intra:70.4% inter:75.1%
[libx264 @ 000002911df99380] coded y,uvDC,uvAC intra: 83.4% 100.0% 100.0% inter: 0.5% 0.8% 0.4%
[libx264 @ 000002911df99380] i16 v,h,dc,p: 41% 17%  5% 37%
[libx264 @ 000002911df99380] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 28% 10%  3%  4%  5%  5%  5%  6%
[libx264 @ 000002911df99380] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42% 28%  6%  3%  5%  5%  5%  4%  3%
[libx264 @ 000002911df99380] i8c dc,h,v,p: 69%  6%  6% 19%
[libx264 @ 000002911df99380] Weighted P-Frames: Y:0.2% UV:0.2%
[libx264 @ 000002911df99380] ref P L0: 69.5%  9.9% 18.8%  1.8%  0.0%
[libx264 @ 000002911df99380] ref B L0: 83.8% 16.0%  0.2%
[libx264 @ 000002911df99380] ref B L1: 96.7%  3.3%
[libx264 @ 000002911df99380] kb/s:30742.34
split_video0.mkv 2021-01-11 17:08:05,056 INFO     dandere2x_logger.py set_dandere2x_logger: Dandere2x Console Logger Set
split_video0.mkv 2021-01-11 17:08:05,056 INFO     dandere2x_logger.py set_dandere2x_logger: Dandere2x Console Logger Set
setting json {'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10', 'profile': 'High', 'codec_type': 'video', 'codec_time_base': '0/2', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1920, 'height': 1080, 'coded_width': 1920, 'coded_height': 1088, 'has_b_frames': 2, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '16:9', 'pix_fmt': 'yuv420p', 'level': 61, 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'true', 'nal_length_size': '4', 'r_frame_rate': '1000/1', 'avg_frame_rate': '0/0', 'time_base': '1/1000', 'start_pts': 3, 'start_time': '0.003000', 'bits_per_raw_sample': '8', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'ENCODER': 'Lavc58.47.105 libx264', 'DURATION': '00:00:12.142000000'}}, {'index': 1, 'codec_name': 'vorbis', 'codec_long_name': 'Vorbis', 'codec_type': 'audio', 'codec_time_base': '1/44100', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'sample_fmt': 'fltp', 'sample_rate': '44100', 'channels': 2, 'channel_layout': 'stereo', 'bits_per_sample': 0, 'r_frame_rate': '0/0', 'avg_frame_rate': '0/0', 'time_base': '1/1000', 'start_pts': 0, 'start_time': '0.000000', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'ENCODER': 'Lavc58.47.105 libvorbis', 'DURATION': '00:00:12.139000000'}}], 'format': {'filename': 'D:\\Programs\\dandere2x\\3.0\\3.0\\workspace\\gui\\split_video0.mkv', 'nb_streams': 2, 'nb_programs': 0, 'format_name': 'matroska,webm', 'format_long_name': 'Matroska / WebM', 'start_time': '0.000000', 'duration': '12.142000', 'size': '51004253', 'bit_rate': '33605174', 'probe_score': 100, 'tags': {'ENCODER': 'Lavf58.26.101'}}}
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "dandere2x\__init__.py", line 56, in run
  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 61, in run
  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 58, in _pre_process
  File "dandere2x\dandere2x_service\__init__.py", line 43, in __init__
  File "dandere2x\dandere2x_service\dandere2x_service_context.py", line 57, in __init__
  File "dandere2x\dandere2xlib\wrappers\ffmpeg\videosettings.py", line 27, in __init__
  File "fractions.py", line 156, in __new__
ZeroDivisionError: Fraction(0, 0)
```

**Comment by akai-katto** [comment]
What's happening is ffprobe is receiving 0/ 0 for width and height. If you know how to re-encode a video, you can re-encode it, or wait for me to implement the backup "width height finder" when the main fails. I haven't seen this error before

**Comment by TheProgramableTurtle** [comment]
I'll try re-encoding it. Just to be sure, what codecs does dandare2x support? I looked through the readme and Wiki but couldn't find anything.

**Comment by TheProgramableTurtle** [comment]
Ok so encoding with H.264 works but the output is literally the exact same as the input but covered in weird artifacts. Going to try messing around with it a bit.

**Comment by TheProgramableTurtle** [comment]
Holy moly is that a major improvement. I re-formatted the video so it was the actual resolution and framerate. Dandere2x took about 30 seconds to finish instead of the previous 30 minutes and it worked great. There are still black squares though but it seems that's already a known issue. I'll leave this open for the original issue.

**Comment by akai-katto** [comment]
What's your graphics card? The black squares may be coming from a lack of sufficient vram, or just dandere2x having issues. You can try turning "quality" in the GUI up to a higher setting if you haven't already done that. 

Also, thanks for your words. I'm really happy to hear you find the time speedup dramatic.

**Comment by TheProgramableTurtle** [comment]
I've got an RX 580 with 8GB, I'll try increasing the quality setting. The source video is very poor quality so I'm not expecting anything particularly amazing.

**Comment by akai-katto** [comment]
Closing this ticket for now, let me know / create a new ticket if there's more issues.
