### ISSUE TITLE
cv2.error: OpenCV(3.4.11) error: (-2:Unspecified error) The function is not implemented.

### ISSUE THREAD

**Issue by andykais** [akai-katto/dandere2x#173]
Running `(venv)  andrew  src  python main.py` from master fails.
- waifu2x-ncnn-vulkan `20210102-1`
- python ` 3.9.0`
```
split_video0.mkv 2021-01-14 13:39:50,025 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12510] 99%]    Average of Last 10 Frames: 0.07 sec / frame
split_video0.mkv 2021-01-14 13:40:01,416 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12520] 99%]    Average of Last 10 Frames: 1.14 sec / frame
split_video0.mkv 2021-01-14 13:40:12,306 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12530] 99%]    Average of Last 10 Frames: 1.09 sec / frame
Exception in thread Min Disk Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/andrew/Code/releases/dandere2x/src/dandere2x/dandere2x_service/core/min_disk_usage.py", line 91, in run
    self.progressive_frame_extractor.release_capture()
  File "/home/andrew/Code/releases/dandere2x/src/dandere2x/dandere2xlib/wrappers/cv2/progressive_frame_extractor.py", line 32, in release_capture
    cv2.destroyAllWindows()
cv2.error: OpenCV(3.4.11) /tmp/pip-req-build-p2crtnp0/opencv/modules/highgui/src/window.cpp:652: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

split_video0.mkv 2021-01-14 13:40:23,175 INFO     merge.py join    : Join called.
split_video0.mkv 2021-01-14 13:40:28,056 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12540] 99%]    Average of Last 10 Frames: 1.57 sec / frame
split_video0.mkv 2021-01-14 13:40:40,252 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12550] 99%]    Average of Last 10 Frames: 1.22 sec / frame
split_video0.mkv 2021-01-14 13:40:54,671 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12560] 99%]    Average of Last 10 Frames: 1.44 sec / frame
split_video0.mkv 2021-01-14 13:41:01,473 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12570] 99%]    Average of Last 10 Frames: 0.68 sec / frame
split_video0.mkv 2021-01-14 13:41:04,862 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12580] 99%]    Average of Last 10 Frames: 0.34 sec / frame
split_video0.mkv 2021-01-14 13:41:09,439 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12590] 99%]    Average of Last 10 Frames: 0.46 sec / frame
split_video0.mkv 2021-01-14 13:41:11,539 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12600] 99%]    Average of Last 10 Frames: 0.21 sec / frame
split_video0.mkv 2021-01-14 13:41:16,297 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12610] 99%]    Average of Last 10 Frames: 0.48 sec / frame
split_video0.mkv 2021-01-14 13:41:18,454 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12620] 99%]    Average of Last 10 Frames: 0.22 sec / frame
split_video0.mkv 2021-01-14 13:41:19,790 INFO     status_thread.py run     : [File: split_video0.mkv][Frame: [12630] 99%]    Average of Last 10 Frames: 0.13 sec / frame
split_video0.mkv 2021-01-14 13:41:19,969 INFO     pipe_thread.py kill    : Kill called.
split_video0.mkv 2021-01-14 13:41:22,081 INFO     merge.py join    : Join finished.
split_video0.mkv 2021-01-14 13:41:22,081 INFO     residual.py join    : Method called.
split_video0.mkv 2021-01-14 13:41:22,081 INFO     residual.py join    : Join finished.
split_video0.mkv 2021-01-14 13:41:22,081 INFO     status_thread.py join    : Join called.
split_video0.mkv 2021-01-14 13:41:22,081 INFO     status_thread.py join    : Join finished.
QThread::start: Thread termination error (No such process)
```
the `Exception in thread Min Disk Thread:` error is reported several times in the logs. The gui reports a successful upscale 
![screenshot(267)](https://user-images.githubusercontent.com/6627147/104646556-9627f080-567e-11eb-983b-9928c64efa42.png)

**Comment by akai-katto** [comment]
I get this too, I think it's from a change in opencv dependency. I'll look into rebuilding dandere2x with the new opencv.

**Comment by akai-katto** [comment]
The video completes for you, right? It does for me.

**Comment by andykais** [comment]
not really :cry: . The output is a 293 byte video file.
```
-rw-r--r-- 1 andrew users 76M Jan  9 01:25 Zatch Bell Episode 001 English Dubbed.flv
-rw-r--r-- 1 andrew users 293 Jan 14 13:57 Zatch Bell Episode 001 English Dubbed_[vulkan][s2][n3][b20][q98].mkv
```

**Comment by akai-katto** [comment]
> 
> 
> not really 😢 . The output is a 293 byte video file.
> 
> ```
> -rw-r--r-- 1 andrew users 76M Jan  9 01:25 Zatch Bell Episode 001 English Dubbed.flv
> -rw-r--r-- 1 andrew users 293 Jan 14 13:57 Zatch Bell Episode 001 English Dubbed_[vulkan][s2][n3][b20][q98].mkv
> ```

https://github.com/akai-katto/dandere2x/releases/tag/3.0.2

I re-built the last binary using a new opencv dependency, let me know if this still causes issues.

**Comment by akai-katto** [comment]
I just saw that you're on linux - I've moved the dependency change to master, try rebuilding / installing your env using the new cv2 dependency. I'll hop on my linux distro and see if this error exists there also.
