### ISSUE TITLE
externals\ffprobe.exe does not exist!

### ISSUE THREAD

**Issue by FranzDeschler** [akai-katto/dandere2x#199]
I just downloaded the latest release (3.2) as .zip file, extracted the .zip file and tried to process the yn_moving_480.mkv file in the workspace.
In the console, I get this error:

`Calling GUI start.
config file: singleprocess
config file: singleprocess
config file: singleprocess
Traceback (most recent call last):
  File "gui_driver.py", line 209, in press_upscale_button
  File "gui_driver.py", line 24, in __init__
  File "dandere2x\__init__.py", line 26, in __init__
  File "dandere2x\dandere2x_service\service_types\singleprocess_service.py", line 22, in __init__
  File "dandere2x\dandere2xlib\wrappers\ffmpeg\ffmpeg.py", line 101, in is_file_video
AssertionError: G:\Downloads\dandere2x\externals\ffprobe.exe does not exist!
`

**Comment by akai-katto** [comment]
You need to hit the "download externals" button before running the first upscale. You only need to do this once
