### ISSUE TITLE
Can't find files?

### ISSUE THREAD

**Issue by starinspace** [akai-katto/dandere2x#204]
I don't know why, but I get this problem when trying to upscale, I have tried Caffe, Vulkan and Cpp. It does say "Det går inte att hitta filen", (Can't find the file).

```
Exception in thread Gui Call:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "dandere2x\dandere2x_service\__init__.py", line 71, in run
  File "dandere2x\dandere2x_service\core\min_disk_usage.py", line 102, in extract_initial_frames
  File "dandere2x\dandere2xlib\wrappers\cv2\progressive_frame_extractor.py", line 54, in next_frame
  File "dandere2x\dandere2xlib\utils\dandere2x_utils.py", line 145, in rename_file_wait
FileNotFoundError: [WinError 2] Det går inte att hitta filen: 'D:\\Video\\Muumipeikko Pyrstötähti\\dandere2x-3.2\\workspace\\gui\\subworkspace\\inputs\\frame_temp_1.jpg' -> 'D:\\Video\\Muumipeikko Pyrstötähti\\dandere2x-3.2\\workspace\\gui\\subworkspace\\inputs\\frame1.jpg'
root 2021-04-22 17:29:57,738 INFO     ffmpeg.py migrate_tracks_contextless: Migrating tracks D:\Video\Muumipeikko Pyrstötähti\dandere2x-3.2\externals\ffmpeg.exe -i D:\Video\Muumipeikko Pyrstötähti\dandere2x-3.2\workspace\gui\non_migrated.mkv -i D:\Video\Muumipeikko Pyrstötähti\title_t00 (1)-001.mkv -map 0:v? -map 1:a? -map 1:s? -map 1:d? -map 1:t? -c copy -y D:\Video\Muumipeikko Pyrstötähti\title_t00 (1)-001_[converter_cpp][s2][n3][b20][q98].mkv
root 2021-04-22 17:29:57,754 INFO     ffmpeg.py migrate_tracks_contextless: Writing files to D:\Video\Muumipeikko Pyrstötähti\dandere2x-3.2\workspace\gui
root 2021-04-22 17:29:57,754 INFO     ffmpeg.py migrate_tracks_contextless: Migrate Command: D:\Video\Muumipeikko Pyrstötähti\dandere2x-3.2\externals\ffmpeg.exe -i D:\Video\Muumipeikko Pyrstötähti\dandere2x-3.2\workspace\gui\non_migrated.mkv -i D:\Video\Muumipeikko Pyrstötähti\title_t00 (1)-001.mkv -map 0:v? -map 1:a? -map 1:s? -map 1:d? -map 1:t? -c copy -y D:\Video\Muumipeikko Pyrstötähti\title_t00 (1)-001_[converter_cpp][s2][n3][b20][q98].mkv
root 2021-04-22 17:29:57,982 INFO     ffmpeg.py migrate_tracks_contextless: Finished migrating to file: D:\Video\Muumipeikko Pyrstötähti\title_t00 (1)-001_[converter_cpp][s2][n3][b20][q98].mkv
```

**Comment by akai-katto** [comment]
Change the workspace to something that doesn't contain non-ascii characters, the german characters are causing issues. I need to address this

**Comment by starinspace** [comment]
That worked so much better without åäö. :)
