### ISSUE TITLE
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'D:\\Guillaume\\Téléchargements\\Dandere2x\\workspace\\gui\\subworkspace\\inputs\\frame_temp_1.png'

### ISSUE THREAD

**Issue by mirandaguillaume** [akai-katto/dandere2x#217]
Hi ! I have this issue when trying to use Dandere2x on Windows

`Exception in thread Gui Call:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "dandere2x\dandere2x_service\__init__.py", line 87, in run
  File "dandere2x\dandere2x_service\core\min_disk_usage.py", line 102, in extract_initial_frames
  File "dandere2x\dandere2xlib\wrappers\cv2\progressive_frame_extractor.py", line 51, in next_frame
  File "dandere2x\dandere2xlib\utils\dandere2x_utils.py", line 145, in rename_file_wait
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'D:\\Guillaume\\Téléchargements\\Dandere2x\\workspace\\gui\\subworkspace\\inputs\\frame_temp_1.png' -> 'D:\\Guillaume\\Téléchargements\\Dandere2x\\workspace\\gui\\subworkspace\\inputs\\frame1.png'`

**Comment by akai-katto** [comment]
Which version is this? Can you try the latest?

**Comment by CareBearsAICAL** [comment]
@mirandaguillaume The same thing happened to me once. Just don't use a route that uses acute accents. " **´** "
