### ISSUE TITLE
Error I keep getting

### ISSUE THREAD

**Issue by DillFrescott** [akai-katto/dandere2x#225]
Exception in thread Thread-16:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "dandere2x\__init__.py", line 57, in run
  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 61, in run
  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 33, in _pre_process
  File "dandere2x\dandere2x_service\service_types\dandere2x_service_interface.py", line 79, in _check_and_fix_resolution
  File "dandere2x\dandere2xlib\wrappers\ffmpeg\ffmpeg.py", line 138, in append_resize_filter_to_pre_process
KeyError: '-vf'

**Comment by akai-katto** [comment]
Woops, I forgot to test multiprocessing out. I'll get an update out for you, as I removed this config option when I changed the way dandere2x works.

**Comment by DillFrescott** [comment]
@akai-katto Awesome! Thank you!!!

**Comment by DillFrescott** [comment]
@akai-katto Ok. I replaced the config with that and now I'm getting this error,

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\micro\Desktop\yt5s.com-Kono Subarashii Sekai ni Shukufuku wo! Ep 3 EXPLOSSSIOOON~~(720p).mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2020-03-02T11:41:24.000000Z
  Duration: 00:03:39.82, start: 0.000000, bitrate: 911 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 779 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2020-03-02T11:41:24.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/02/2020.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2020-03-02T11:41:24.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/02/2020.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
[AVFilterGraph @ 00000298e68354c0] No such filter: ''.77 bitrate=N/A speed=N/A
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[libvorbis @ 00000298e6060f80] 41 frames left in the queue on closing
Conversion failed!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "dandere2x\__init__.py", line 57, in run
  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 61, in run
  File "dandere2x\dandere2x_service\service_types\multiprocess_service.py", line 42, in _pre_process
  File "dandere2x\dandere2xlib\wrappers\ffmpeg\ffmpeg.py", line 205, in divide_and_reencode_video
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['C:\\Users\\micro\\Downloads\\3.4b\\externals\\ffmpeg.exe', '-i', 'C:\\Users\\micro\\Desktop\\yt5s.com-Kono Subarashii Sekai ni Shukufuku wo! Ep 3 EXPLOSSSIOOON~~(720p).mp4', '-f', 'segment', '-segment_time', '73', '-r', '23.976023976023978', '-pix_fmt', 'rgba64le', '-vsync', 'cfr', '-crf', '1', '-vf', '', 'C:\\Users\\micro\\Downloads\\3.4b\\workspace\\gui\\split_video%d.mkv']' returned non-zero exit status 1.

**Comment by akai-katto** [comment]
I got this error too.. i'm going to try "null" as the filter 

(sorry I didn't test this out myself). The issue is that the program expects **a** filter there, and I removed the filters needed during covnersion, and re-adding a filter of ' ' broke it. I think 'null' might fix it.
