### ISSUE TITLE
ffprobe.exe does not exist

### ISSUE THREAD

**Issue by YuanlinLi** [akai-katto/dandere2x#247]
Traceback (most recent call last):
  File "gui_driver.py", line 209, in press_upscale_button
  File "gui_driver.py", line 24, in __init__
  File "dandere2x\__init__.py", line 26, in __init__
  File "dandere2x\dandere2x_service\service_types\singleprocess_service.py", line 22, in __init__
  File "dandere2x\dandere2xlib\wrappers\ffmpeg\ffmpeg.py", line 101, in is_file_video
AssertionError: D:\Dandere2x - Fast Waifu2x Video Upscaling\3.3\externals\ffprobe.exe does not exist!

**Comment by YuanlinLi** [comment]
closed
