### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by unfa** [akai-katto/dandere2x#253]
I am trying to upscale an MKV file, but Dandere2X show me this output after pressing "Upscale" in the GUI:

```
threading at start of runtime
[<_MainThread(MainThread, started 5788)>, <Dandere2x(dandere2x_thread, started 31064)>]
creating of C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\merged\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\debug\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\pframe_data\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\inputs\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\fade_data\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\encoded\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\residual_upscaled\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\console_output\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\compressed_static\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\temp_image_folder\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\correction_data\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\residual_data\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\residual_images\ failed
Creation of the directory C:\Users\unfa\Software\Waifu2X\dandere2x\release\workspace\default\compressed_moving\ failed
Exception in thread dandere2x_thread:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "dandere2x.py", line 244, in run
  File "dandere2x.py", line 100, in __setup_jobs
  File "dandere2xlib\mindiskusage.py", line 31, in __init__
  File "wrappers\ffmpeg\progressive_frame_extractor_ffmpeg.py", line 57, in start_task
  File "C:\Users\windwoz\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 216: character maps to <undefined>
```

**Comment by eoiz** [comment]
Are you running dandere2x as admin?

**Comment by unfa** [comment]
I was not. Didn't know it's necessary. Why is that?

**Comment by eoiz** [comment]
Where is the dander2x folder? It need to create files and folders to run...
