### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/valtok/dandere/src/workspace/gui'

### ISSUE THREAD

**Issue by ValtokIsHere** [akai-katto/dandere2x#254]
installed everything, ran main.py and got this

```
valtok@pop-os:~/dandere/src$ python3 main.py
version 3.3
root 2022-08-08 01:07:35,274 INFO     dandere2x_logger.py set_dandere2x_logger: Dandere2x Console Logger Set
Calling GUI start.
config file: singleprocess
config file: singleprocess
config file: singleprocess
root 2022-08-08 01:07:58,324 INFO     yaml_utils.py load_executable_paths_yaml: main_path option /usr/bin did not work, trying the next main_path option
root 2022-08-08 01:07:58,325 INFO     yaml_utils.py load_executable_paths_yaml: Main path /home/valtok/dandere/src loaded executable_paths.yaml successfully. 
attempting to make or clear /home/valtok/dandere/src/workspace/gui
Traceback (most recent call last):
  File "/home/valtok/dandere/src/gui_driver.py", line 27, in run
    self.service_request.make_workspace()
  File "/home/valtok/dandere/src/dandere2x/dandere2x_service_request.py", line 165, in make_workspace
    os.mkdir(self.workspace)
FileNotFoundError: [Errno 2] No such file or directory: '/home/valtok/dandere/src/workspace/gui'

```

**Comment by akai-katto** [comment]
Try creating the missing directory manually

**Comment by akai-katto** [comment]
https://github.com/akai-katto/dandere2x/tree/macosport

Try this branch actually? I dont have access to my linux machine at the moment, but my memory recalls that the macos version worked on ubuntu

**Comment by ValtokIsHere** [comment]
> Try creating the missing directory manually

```
valtok@pop-os:~/dandere/src$ python3 main.py
version 3.3
root 2022-08-08 11:30:52,938 INFO     dandere2x_logger.py set_dandere2x_logger: Dandere2x Console Logger Set
Traceback (most recent call last):
  File "/home/valtok/dandere/src/main.py", line 50, in <module>
    main()
  File "/home/valtok/dandere/src/main.py", line 43, in main
    start_gui()
  File "/home/valtok/dandere/src/main.py", line 22, in start_gui
    from gui_driver import gui_start
  File "/home/valtok/dandere/src/gui_driver.py", line 14, in <module>
    from gui.Dandere2xGUI import Ui_Dandere2xGUI
ModuleNotFoundError: No module named 'gui'

```

im using the macos version actually, ill try using a older version

**Comment by CoWinkKeyDinkInc** [comment]
> Try creating the missing directory manually

creating the missing directories solved this issue for me

**Comment by akai-katto** [comment]
Going to close this issue unless this solution doesnt work for you 

> > Try creating the missing directory manually
> 
> creating the missing directories solved this issue for me
