### ISSUE TITLE
Errors on macOS

### ISSUE THREAD

**Issue by kmhcreative** [akai-katto/dandere2x#266]
Downloaded the 3.6.1b "mac release" to my **M1 Mac running Big Sur 11.6.8** and, after overriding Gatekeeper to run it, I get the GUI but it won't work.  First I had to go into the sub-folders and override Gatekeeper for the other binaries.  Then I get this in the terminal:

```
root 2022-10-03 14:11:33,967 ERROR    dandere2x_cpp.py run     : D2xcpp ended unexpectedly.
root 2022-10-03 14:11:33,971 ERROR    dandere2x_cpp.py run     : Dandere2x will stop the current session.
Exception in thread Dandere2xCpp:
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "dandere2x/dandere2x_service/core/dandere2x_cpp.py", line 70, in run
Exception
```
I don't know what to do with that.  I ultimately just installed Dandere2x vie the Homebrew method, which works.

A separate issue is if you click the "Download Externals" it will download the Windows EXE files.  I also assume there are no macOS versions of "Waifu2x-Caffe" and "Waifu2x-Converter-CPP" but they still appear in the "Waifu2x Type" drop-down.  Selecting either of them makes it throw an exception because they don't exist.  I figured out where in the "Dandere2xGUI.py" file I could remove the text, but that just leaves two blank options in the drop-down list.

**Comment by akai-katto** [comment]
Hi, did you run the bash install script for unix-like systems? It's called `unix_setup.sh"

**Comment by kmhcreative** [comment]
The terminal output above is from the [prebuilt Mac version](https://github.com/akai-katto/dandere2x/releases/tag/3.6.1b) in releases.  When I couldn't get that to work I went the Homebrew route, and yes I ran the "unix_setup.sh" script, which works.

Is the prebuilt "mac release" a self-contained (pyinstaller) app, or is it running the Python installed in the OS?  Because my OS version is Python 2.7.16, while the Homebrew one is Python 3.10.7.  I never changed my PATH to make the Homebrew version the default Python, if that matters.

**Comment by akai-katto** [comment]
Sorry, I ran into a medical emergency and didn't respond. The prebuilt uses a prebuilt c++ binary that I'm guessing isn't working on your system, for some reason I'm not sure of.

**Comment by sveinbjornpalsson** [comment]
Yeah using the mac release is totally not worth it. 
It's broken and hard to understand why or fix, while building the app according to the instructions is way easier.
And with both, you end up with the same gui.
And the more recent release has major improvements, it seems.
