### ISSUE TITLE
I keep getting "Exception: processing type not found single" on Google Colab

### ISSUE THREAD

**Issue by misaalanshori** [akai-katto/dandere2x#268]
I'm trying to run this on Google Colab but I kept getting this error:
```
p4 -o ./vidup.mp4
version 3.3
root 2022-10-08 06:13:34,700 INFO     dandere2x_logger.py set_dandere2x_logger: Dandere2x Console Logger Set
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 45, in main
    cli_start()
  File "main.py", line 11, in cli_start
    root_service_request = Dandere2xServiceRequest.load_from_args(args=args)
  File "/content/dandere2x/src/dandere2x/dandere2x_service_request.py", line 112, in load_from_args
    processing_type=ProcessingType.from_str(args.processing_type),
  File "/content/dandere2x/src/dandere2x/dandere2x_service_request.py", line 22, in from_str
    raise Exception("processing type not found %s" % input)
Exception: processing type not found single
/content/dandere2x/src#
```
Changing processing type to multi didn't do anything. 

Also this is version 3.6b, because I was having another problem on the latest version where pip3 install -r requirements.txt was taking a really long time downloading multiple versions of the same library.

I'm stuck right now, I'm not sure if the problem is with Colab, or if I missed something

**Comment by misaalanshori** [comment]
oh its supposed to be "singleprocess" or "multiprocess"
