### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by ehobson** [akai-katto/dandere2x#289]
When attempting to run program, receive following error at launch:

```
Traceback (most recent call last):
  File "/home/me/Videos/Dandere/dandere2x-master/src/main.py", line 50, in <module>
    main()
  File "/home/me/Videos/Dandere/dandere2x-master/src/main.py", line 43, in main
    start_gui()
  File "/home/me/Videos/Dandere/dandere2x-master/src/main.py", line 22, in start_gui
    from gui_driver import gui_start
  File "/home/me/Videos/Dandere/dandere2x-master/src/gui_driver.py", line 7, in <module>
    from PyQt6 import QtCore, QtGui
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/me/.local/lib/python3.11/site-packages/PyQt6/Qt/lib/libQt6Core.so.6)
```

The glibc_2.25 package does not seem to be available for any version of Ubuntu. How can this requirement be satisfied?

**Comment by akai-katto** [comment]
What version of ubuntu are you on? 

And btw, you can use the cli for dandere2x, if the gui isn't working. 

`python3 main.py -p singleprocess -ws ./workspace/ -i /host/[your_video.mkv] -o /host/[your_output.mkv]`
