### ISSUE TITLE
PIL - BrokenPipeError: [Errno 32] Broken pipe on Linux

### ISSUE THREAD

**Issue by DemersM** [akai-katto/dandere2x#300]
I have installed on Ubuntu 22.04 in conda environnement with pyaml upgraded to 6.0.1 because of incompatibility problem with cython 3.0

I got the following error few seconds after starting the script

```
Exception in thread Pipe Thread:
Traceback (most recent call last):
  File "/home/maxime/miniconda3/envs/videoproc/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/maxime/videoproc/dandere2x/src/dandere2x/dandere2xlib/wrappers/ffmpeg/pipe_thread.py", line 48, in run
    img.save(self.ffmpeg_pipe_subprocess.stdin, format="jpeg", quality=100)
  File "/home/maxime/miniconda3/envs/videoproc/lib/python3.11/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/home/maxime/miniconda3/envs/videoproc/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 805, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/home/maxime/miniconda3/envs/videoproc/lib/python3.11/site-packages/PIL/ImageFile.py", line 517, in _save
    _encode_tile(im, fp, tile, bufsize, fh)
  File "/home/maxime/miniconda3/envs/videoproc/lib/python3.11/site-packages/PIL/ImageFile.py", line 544, in _encode_tile
    errcode = encoder.encode_to_file(fh, bufsize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
```

Anyone could help with this issue?

**Comment by DemersM** [comment]
It turns out the problem was the libx264 encoder was not enabled in my ffmpeg build

**Comment by DemersM** [comment]
It turns out the problem was that the libx264 encoder was not enabled in my ffmpeg build
